more error handling

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -22,11 +22,16 @@ else
 	make re CC=clang -C repo
 fi
 
+if [ ! "$?" -eq "0" ]; then
+	echo -e "${red}compilation error: abort${reset}"
+	exit 1
+fi
+
 if [ -n "$COMMAND" ]; then
 	printf "${blue}running command '$COMMAND'${reset}\n";
 	cd repo && $COMMAND
 elif [ -n "$BIN_FILE" ]; then
-	printf "${blue}running simple valgrind $BIN_FILE${reset}\n"
+	printf "${blue}running simple 'valgrind $BIN_FILE'${reset}\n"
 	#valgrind $BIN_FILE
 	find repo -type f -name $BIN_FILE -exec valgrind {} \;
 else
